### ISSUE TITLE
ETA on workshop participants announcement?

### ISSUE THREAD

**Issue by mjy** [phenoscape/KB-DataFest-2017#4]
Hi @hlapp, @tjv, curious as to whether you have a firm date for announcing participants?  Lots of logistics for alternate planning coming up quickly.

thanks!

**Comment by hlapp** [comment]
Hi @mjy - we're intending to notify applicants starting next week. BTW @tjv is not part of the organizing team. (You read the CfP? 😏 )

**Comment by mjy** [comment]
Thanks.  Sorry for the incorrect include, just saw his commit here and assumed!
