### ISSUE TITLE
Recommendations for travel dates?

### ISSUE THREAD

**Issue by mjy** [phenoscape/KB-DataFest-2017#5]
I'm assuming these details are all coming soon, but trying to get the flight booked so:

I assume we should plan to arrive on the 10th?

Should we also assume to depart on the 15th, the 14th?

**Comment by hlapp** [comment]
Hi @mjy - sorry if that wasn't clear from the acceptance letter. Yes, arrival on the 10th. Departure in the evening or afternoon of the 14th, if possible. Otherwise on the 15th.
